[versions]
maven-group = "net.krlite"
archives-name = "equator"
mod = "2.6.4"

archives-animation-name = "equator-animation"
archives-math-name = "equator-math"
archives-visual-name = "equator-visual"

minecraft = "1.20.1"
yarn = "1.20.1+build.10"
forge = "1.20.1-47.2.32"
architectury-loom = "1.5-SNAPSHOT"

mixbox = "2.0.0"
word-wrap = "0.1.12"
guava-mini = "0.1.4"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }

mixbox = { group = "com.scrtwpns", name = "mixbox", version.ref = "mixbox" }
word-wrap = { group = "com.github.davidmoten", name = "word-wrap", version.ref = "word-wrap" }
guava-mini = { group = "com.github.davidmoten", name = "guava-mini", version.ref = "guava-mini" }

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
